### ISSUE TITLE
nuke 12.1 Unable to work

### ISSUE THREAD

**Issue by justinli** [luckylyk/hotbox_designer#10]
nuke 12.1 Unable to work

**Comment by vincentgires** [comment]
Could you try with the latest commit?
There was indeed something broken since Nuke 12. I could not try on 12.1 yet but this is working on 11.3v6 and 12.0v5 now.
If you have still issue on 12.1, please provide the error message and operating system you use.

**Comment by luckylyk** [comment]
Thanks Guile !

Justin, can you tell us if that works ? Like that I can close the ticket.

**Comment by justinli** [comment]
Traceback (most recent call last):
  File "C:/Users/lizhaohui/.nuke/menu.py", line 16, in <module>
    nuke_app = Nuke()
  File "C:/Users/lizhaohui/.nuke/nukescripts\hotbox_designer\applications.py", line 26, in __init__
    self.main_window = self.get_main_window()
  File "C:/Users/lizhaohui/.nuke/nukescripts\hotbox_designer\applications.py", line 152, in get_main_window
    for widget in QtWidgets.QApplication.instance().topLevelWidgets():
AttributeError: 'PySide2.QtCore.QCoreApplication' object has no attribute 'topLevelWidgets'

**Comment by vincentgires** [comment]
The problem is that hotbox designer needs Nuke as parent window and when Nuke calls the content of init.py or menu.py, it does it before the graphical window is created, and the parent window does not exist yet. So for me, the ticket can be clause since this is a problem on the Nuke side that should provide properly a way to access to the main window at startup.
However, an easy fix is to wait a bit before creating HotboxManager. Here is a code you can use instead in Nuke's menu.py.
I don't like it but maybe we could edit the readme with this dirty fix to avoid other to get the same issue.

```python
from PySide2.QtCore import QTimer
import nuke
import hotbox_designer

from hotbox_designer.applications import Nuke
from hotbox_designer.manager import HotboxManager

def add_hotbox():
    nuke_app = Nuke()
    hotbox_manager = HotboxManager(nuke_app)

    nuke_menu = nuke.menu('Nuke')
    menu = nuke_menu.addMenu('Hotbox Designer')
    menu.addCommand(
        name='Manager',
        command=hotbox_manager.show)
    nuke_app.create_menus()

if nuke.GUI:
    # Getting QMainWindow that hotbox_designer needs must be done after
    # some GUI calls to work
    QTimer.singleShot(0, lambda: add_hotbox())

```

**Comment by luckylyk** [comment]
![image](https://user-images.githubusercontent.com/25019043/76785524-ff538480-678b-11ea-8f61-9177495ba637.png)
Thanks Vincent ! You rock !

**Comment by luckylyk** [comment]
readme updated !
![image](https://mouse.latercera.com/wp-content/uploads/2017/03/ryu-kick.gif)
